### PR TITLE
fix: disable cleanup when CR is auto generated

### PR DESCRIPTION
**Pull request by pb82**
removes all finalizers and disables cleanup if the CR was auto generated. Finalizers cause issues with namespace deletion and without the finalizer we will need to refactor to using owner references for all resources to do cleanup.

### CODE REVIEW

**Comment by machi1990** [comment]
Will this also perform the migration of existing auto created CRs?

**Comment by pb82** [comment]
@machi1990 no, good point. I'll add that.

**Comment by pb82** [comment]
@machi1990 this is added now

**Review by vmanley — APPROVED** [review]
LGTM. Worked as expected running with user-created and operator-created CRs

**Pull request merged**
