### PR TITLE
Migrate new PVC to existing PV

### PR DESCRIPTION
**Pull request by vmanley**
The purpose of this change to allow the Operator to create a new Persistent Volume Claim (PVC) that can be bound to an existing Persistent Volume (PV). This is needed to address the issue where the Operator creates a duplicate PVC and PV when the Operator migrates resource names to new generic defaults.

Verification
Note: Requires OSD cluster capable to creating PVs

- Install v3.0.16 of the Operator. Can be installed by applying the following catalogSource to your cluster:
```
apiVersion: operators.coreos.com/v1alpha1
kind: CatalogSource
metadata:
  name: observability-operator-manifests
  namespace: <insert-namespace>
spec:
  sourceType: grpc
  image: quay.io/rhoas/observability-operator-index:v3.0.16
```

- Allow Operator to fully install including creation of PVC (named: `managed-services-prometheus-kafka-prometheus-0`) and accompanying PV (note which PV is bound to created PVC). Check Storage tab of console UI

- Uninstall the Operator and run this PR locally against the cluster. Alternatively you can apply the following catalogSource to upgrade the Operator to include this change:
```
apiVersion: operators.coreos.com/v1alpha1
kind: CatalogSource
metadata:
  name: observability-operator-manifests
  namespace: <insert-namespace>
spec:
  sourceType: grpc
  image: quay.io/vmanley/observability-operator-index:v4.0.0
```

- In the Observability CR, adjust the resync period down (`30s` is good) to trigger a resync (This step will be obsolete once [PR 151](https://github.com/redhat-developer/observability-operator/pull/151) is merged)

- Once stack install is complete, the existing PVC should be deleted and replaced with new PVC named `managed-services-prometheus-observability-prometheus-0`

- Check the persistent volumes. Existing volume is now bound to new PVC named `managed-services-prometheus-observability-prometheus-0`

### CODE REVIEW

**Review by pb82 — APPROVED** [review]

**Comment by vmanley** [comment]
Hey @StevenTobin could you a look over this PR in case I'm overlooking something? It resolves an issue with duplicate PVCs created during resource name migration. New PVC created by OO binds to existing volume. Thanks

**Comment by StevenTobin** [comment]
@vmanley sure, I'll try it out now.

**Comment by StevenTobin** [comment]
PVC renamed and old PVC deleted as expected

```
$ oc get pvc
NAME                                                     STATUS   VOLUME                                     CAPACITY   ACCESS MODES   STORAGECLASS   AGE
managed-services-prometheus-observability-prometheus-0   Bound    pvc-55133dd4-6d18-404c-8041-2c476e93ca1d   250Gi      RWO            gp3            2m9s                                                                               
 ```

**Review by StevenTobin — APPROVED** [review]

**Review by pb82 — APPROVED** [review]

**Comment by vmanley** [comment]
Thanks @StevenTobin @pb82

**Pull request merged**
