### PR TITLE
Resource name migration

### PR DESCRIPTION
**Pull request by pb82**
Migrating all the Kafka specific resources to neutral names. This is achieved by adding a new phase that runs first and deletes any resources (Prometheus CR, service, service account, route) with the old name.

Then continues with the regular phases to restore the resources with the new names.

### CODE REVIEW

**Review by vmanley — COMMENTED** [review]
@pb82 Think this change is ready. One aspect of changing default names to be aware of is the PVCs created by operator can be duplicated. The PVC with old default name would need to be manually deleted

**Comment by pb82** [comment]
@vmanley when installing this version it seems to be using the old names, is that expected? Is the migration only happening on upgrade?

**Comment by vmanley** [comment]
@pb82 Thanks for checking this change. New default names should be used for fresh installs and upgrades. There may be issues with image building process with Operator. Could you try with this index: quay.io/vmanley/observability-operator-index:v3.0.15
Thanks!

**Comment by stehessel** [comment]
@pb82 @vmanley is there anything left that is holding back this PR?

**Comment by vmanley** [comment]
@stehessel Sorry for delay in getting back to you. We're looking to include this in our next release which is being prepared now

**Comment by laurafitzgerald** [comment]
@vmanley is there an upgrade path required here. for example for RHOAM will it upgrade seamlessly or do we need to handle that in any way?

**Comment by vmanley** [comment]
@laurafitzgerald For self-contained the resource names will remain as they are provided by the CR. Migration should not impact self-contained mode. No action should be needed you folks

**Pull request merged**
