### PR TITLE
add toleration for node taint to unblock fluentd pods

### PR DESCRIPTION
**Pull request by StevenTobin**
Add a toleration to the fluentd collector pods to tolerate a taint added to the nodes.

_The toleration added to the clusterLogging CR_

Screenshot from 2022-12-06 12-20-08

_The toleration rendered down to the collector daemonset_

Screenshot from 2022-12-06 12-20-35

### CODE REVIEW

**Review by vmanley — APPROVED** [review]
LGTM. Thanks Steven

**Comment by machi1990** [comment]
I think we need a minor release following this change. wdyt? @StevenTobin @vmanley

**Comment by vmanley** [comment]
@machi1990 We can do that

**Comment by StevenTobin** [comment]
@machi1990 Yeah I already spoke to @vmanley about a minor release yesterday.

**Pull request merged**
